apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      run: movie-deploy
  template:
    metadata:
      labels:
        run: movie-deploy
    spec:
      containers:
      - image: gw1106/movie-app-beta:v1
        name: test
        ports:
        - containerPort: 80
